GPT_MODEL_PATH = "G:\data\\tts\\tool\GPT-SoVITS-beta0128\GPT_weights\\ningning-e15.ckpt"
SOVITS_MODEL_PATH = "G:\data\\tts\\tool\GPT-SoVITS-beta0128\SoVITS_weights\\ningning_e8_s80.pth"
EXAMPLE_WAV = "G:\data\\tts\\tool\GPT-SoVITS-beta0128\output\slicer_opt\stage.wav_1266880_1398080.wav"
EXAMPLE_TEXT = "发了张刚才的自拍，然后我爸我妈说美。"
EXAMPLE_TEXT_LANG = "zh"
OUTPUT_WAV_PATH = "F:\github\study\\ning_agent\\app\\tts\output"