GPT_MODEL_PATH = "GPT_SoVITS/pretrained_models/s2G488k.pth"
SOVITS_MODEL_PATH = "GPT_SoVITS/pretrained_models/s2G488k.pth"
EXAMPLE_WAV = "/Users/viking/ai/study/GPT-SoVITS/GPT_SoVITS/prepare_datasets/stage.wav_1266880_1398080.wav"
EXAMPLE_TEXT = "发了一张刚才的自拍，然后我爸我妈说美"
EXAMPLE_TEXT_LANG = "i18n(\"中文\")"
OUTPUT_WAV_PATH = ""